<?php

namespace app\models\work;

use app\models\common\InvoiceEntry;
use app\models\null\EntryNull;
use app\models\null\InvoiceNull;
use Yii;


class InvoiceEntryWork extends InvoiceEntry
{
	public function getEntryWork()
    {
        $try = $this->hasOne(EntryWork::className(), ['id' => 'entry_id']);
        return $try->all() ? $try : new EntryNull();
    }

    public function getInvoiceWork()
    {
        $try = $this->hasOne(InvoiceWork::className(), ['id' => 'invoice_id']);
        return $try->all() ? $try : new InvoiceNull();
    }


    public function afterDelete()
    {
        $objectEntries = ObjectEntryWork::find()->where(['entry_id' => $this->entry_id])->all();
        foreach ($objectEntries as $one)
        {
            $object = MaterialObjectWork::find()->where(['id' => $one->material_object_id])->one();
            $entry = EntryWork::find()->where(['id' => $one->entry_id])->one();
            if ($one !== null) $one->delete();
            if ($object !== null) $object->delete();
            if ($entry !== null) $entry->delete();
        }

        return parent::afterDelete();
    }


    public function beforeDelete()
    {
        

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
