<?php

namespace app\models\work;

use app\models\common\KindObject;
use Yii;
use yii\helpers\Html;


class KindObjectWork extends KindObject
{
    public $chars;

    public function getCharacteristics()
    {
        $chars = KindCharacteristicWork::find()->where(['kind_object_id' => $this->id])->all();
        $res = '';
        foreach ($chars as $char)
            $res .= $char->characteristicObjectWork->name.'<br>';

        return $res;
    }

    private function IsDuplicateCharacteristic($charName)
    {
        $chars = CharacteristicObjectWork::find()->where(['name' => $charName])->one();
        return $chars !== null;
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        foreach ($this->chars as $char)
        {

            //--Создаем характеристику (или берем старую)--
            $newChar = new CharacteristicObjectWork();
            if ($this->IsDuplicateCharacteristic($char->name)) $newChar = CharacteristicObjectWork::find()->where(['name' => $char->name])->one();
            else
            {
                $newChar->name = $char->name;
                $newChar->value_type = $char->value_type;
                $newChar->save();
            }

            //--Создаем связку Характеристика-Класс--
            $kindChar = new KindCharacteristicWork();
            $kindChar->kind_object_id = $this->id;
            $kindChar->characteristic_object_id = $newChar->id;

            if (KindCharacteristicWork::find()->where(['kind_object_id' => $this->id])->andWhere(['characteristic_object_id' => $newChar->id])->one() !== null)
            {
                Yii::$app->session->setFlash('danger', 'Невозможно присвоить одну и ту же характеристику одному классу');
                return;
            }
            $kindChar->save();


            //--Если вдруг выпадающий список - то идем сюда--
            if ($char->value_type == 7)
            {
                $items = preg_split('/[\n\r]+/', $char->dd_value);
                foreach ($items as $item) {
                    $newDd = new DropdownCharacteristicObjectWork();
                    $newDd->characteristic_object_id = $newChar->id;
                    $newDd->item = $item;
                    $newDd->save();
                }
            }
        }
    }
}
