<?php


namespace app\models\work;


class PatchnotesWork extends \app\models\common\Patchnotes
{
    public $checker;

    public function rules()
    {
        return [
            [['first_number', 'second_number', 'date', 'text'], 'required'],
            [['first_number', 'second_number', 'checker'], 'integer'],
            [['date'], 'safe'],
            [['text'], 'string', 'max' => 10000],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_number' => 'First Number',
            'second_number' => 'Second Number',
            'date' => 'Date',
            'text' => 'Text',
            'checker' => 'Обновить версию?',
        ];
    }



    public function beforeSave($insert)
    {
        $patchs = PatchnotesWork::find()->orderBy(['date' => SORT_DESC])->all();
        if (count($patchs) > 0)
        {
            if ($this->checker === "0")
            {
                $this->first_number = $patchs[0]->first_number;
                $this->second_number = $patchs[0]->second_number + 1;
            }
            else
            {
                $this->first_number = $patchs[0]->first_number + 1;
                $this->second_number = 1;
            }
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}