<?php


namespace app\models\work;

use app\models\common\Subobject;
use Yii;


class SubobjectWork extends Subobject
{
	public $subobjects;

	public function rules()
    {
        return [
            [['name', 'state'], 'required'],
            [['state', 'parent_id', 'entry_id'], 'integer'],
            [['name'], 'string', 'max' => 1000],
            [['characteristics'], 'string', 'max' => 2000],
            [['parent_id'], 'exist', 'skipOnError' => true, 'targetClass' => SubobjectWork::className(), 'targetAttribute' => ['parent_id' => 'id']],
            [['entry_id'], 'exist', 'skipOnError' => true, 'targetClass' => EntryWork::className(), 'targetAttribute' => ['entry_id' => 'id']],
            ['subobjects', 'safe'],
        ];
    }

	public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'characteristics' => 'Characteristics',
            'state' => 'В рабочем состоянии',
            'parent_id' => 'Parent ID',
            'entry_id' => 'Entry ID',
        ];
    }

	public function getStateString()
	{
		return $this->state == 0 ? 'Нерабочий' : 'Рабочий';
	}


	public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if ($this->subobjects !== null && $this->subobjects[0]->name !== '')
        {
            foreach ($this->subobjects as $subobject)
            {
                $newSub = new SubobjectWork();
                $newSub->name = $subobject->name;
                $newSub->characteristics = $subobject->characteristics;
                $newSub->state = 1;
                $newSub->parent_id = $this->id;
                $newSub->save(false);
            }
        }
    }


    public function beforeDelete()
    {
        $subs = SubobjectWork::find()->where(['parent_id' => $this->id])->all();

        foreach ($subs as $one)
            $one->delete();

        return parent::beforeDelete();
    }
}