<?php

namespace app\models\work;

use app\models\common\Auditorium;
use app\models\common\Branch;
use app\models\common\TrainingGroup;
use app\models\common\TrainingGroupLesson;
use app\models\null\BranchNull;
use app\models\null\AuditoriumNull;
use Yii;


class TrainingGroupLessonWork extends TrainingGroupLesson
{
    public $auds;

    public function rules()
    {
        return [
            [['lesson_date', 'lesson_start_time', 'lesson_end_time'], 'string'],
            [['duration', 'training_group_id', 'branch_id'], 'integer'],
            [['auds', 'auditorium_id'], 'safe'],
            [['lesson_start_time'], 'required'],
            ['lesson_start_time', 'time', 'min' => strtotime('08:30'), 'max' => strtotime('20:00')],
            [['training_group_id'], 'exist', 'skipOnError' => true, 'targetClass' => TrainingGroup::className(), 'targetAttribute' => ['training_group_id' => 'id']],
            [['branch_id'], 'exist', 'skipOnError' => true, 'targetClass' => Branch::className(), 'targetAttribute' => ['branch_id' => 'id']],
        ];
    }

    public function getBranchWork()
    {
        $try = $this->hasOne(BranchWork::className(), ['id' => 'branch_id']);
        return $try->all() ? $try : new BranchNull();
    }

    public function getAuditoriumWork()
    {
        $try = $this->hasOne(AuditoriumWork::className(), ['id' => 'auditorium_id']);
        return $try->all() ? $try : new AuditoriumNull();
    }

    public function getFullName()
    {
        $aud = $this->auditorium_id;
        if ($aud === null) return '--- ('.$this->branch->name.')';
        else return $this->auditorium->name.' ('.$this->branch->name.')';
    }

    public function checkValideTime($group_id)
    {
        $lessons = TrainingGroupLesson::find()->where(['!=', 'id', $this->id])->all();
        $result = [];
        foreach ($lessons as $lesson)
        {
            if (($this->lesson_start_time < $lesson->lesson_end_time && $this->lesson_end_time > $lesson->lesson_start_time) && $lesson->lesson_date == $this->lesson_date && $lesson->auditorium_id == $this->auditorium_id)
                $result[] = $lesson->id;
        }
        return $result;
    }

    public function checkCopyLesson()
    {
        $lessons = TrainingGroupLessonWork::find()->where(['training_group_id' => $this->training_group_id])->andWhere(['lesson_date' => $this->lesson_date])->all();
        foreach ($lessons as $lesson) {
            if (substr($lesson->lesson_start_time, 0, 5) == $this->lesson_start_time && substr($lesson->lesson_end_time, 0, 5) == $this->lesson_end_time)
                return false;
        }
        return true;
    }

    public function beforeSave($insert)
    {
        $str = '+'.$this->trainingGroup->trainingProgram->hour_capacity.' minutes';
        $this->lesson_end_time = date("H:i", strtotime($str, strtotime($this->lesson_start_time)));
        $this->duration = 1;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
