<?php

namespace app\models\work;

use app\models\common\Visit;
use app\models\components\Logger;
use Yii;


class VisitWork extends Visit
{
    const ALL = [0, 1, 2, 3]; // считать ВСЕ записи в таблице Visits
    const ONLY_PRESENCE = [0, 2]; //считать только явки и дистант
    const PRESENCE_AND_ABSENCE = [0, 1, 2]; //считать явки, неявки и дистант

    public function beforeDelete()
    {
        Logger::WriteLog(Yii::$app->user->identity->getId(), 'Удалены visit');
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function getPrettyStatus()
    {
        if ($this->status == 1)
            return '<td style="background-color: #DC143C"><font color=white>Н</font></td>';
        else if ($this->status == 2)
            return '<td style="background-color: #183BD9"><font color=white>Д</font></td>';
        else if ($this->status == 3)
            return '<td>--</td>';
        else
            return '<td style="background-color: green"><font color=white>Я</font></td>';
    }

    public function getExcelStatus()
    {
        if ($this->status == 1)
            return 'Н';
        else if ($this->status == 2)
            return 'Д';
        else if ($this->status == 3)
            return '-';
        else
            return 'Я';
    }
}
